traefik:
  retain_ip: true
  health_check:
    port: 8000
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /dashboard/# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
  metadata:
    traefik:
      ssl_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEAySkIZvgsviS8/OXlGmHurcNkKZeWMh+cwz3KZxbgbFpqpBuj
        BMPL80Lt8/ObKfVZzac8JClQEbmQiGOZwuCbdmzVS8bmOlcaWxdO2VYHuLW/Ou+W
        VIGvNTtpJvvoqtxiqWEsh2FzrYrxpqjoqhwFx5N9gprAj+i48AdgUhyokI8AmrpR
        6B24nojfPr+cezsqiPoC+sxQKSzfT/ki33la/FAytUJSZ639/NnkAV7aBLgc70p6
        gCtZaHV+OMBN6jetPA2n8LpTtzsgWOp9CUv/Okl+Cmz1GbdOxH9INGte8F7lIVlm
        XXAvnvyjZNMKPZP3Q2/ML6oVNStfANTNGqfCzCItVfKyuXfd6tpknvtaoYp65sLh
        OvxCw1lc+IIE8m8MQiF52GLfOZsr4Fthy8hg8WwJegBukW1dik8RIFS0LJR9qsX4
        mgsS6JsF41Kc5o1S5HdaLT4Pvq50SAxSMHFHG76pANJWEaKrIVMKz/ALc68rsfsC
        czQzTxVioGxAn6ZaA+tP7MW4o71ZvCxiNs/MdlCvoBzMc9c7xvMym48CUV4S+b08
        fmisR4eL+GvPYuXUehhRQFODjCfzPf9Of08ns2p19nVHR/tP9Txp8atnCsbDUjN7
        eexgnkUIiVyuEWcNyRtDRJpeyt0f0OVnsHR2J22DIu/3N3IPeUJRjGL2nm0CAwEA
        AQKCAgBAZwivnskEX1K6TQgaeDwoGaRZxJRrm79eqsvAUYysZA48WDTK87y6NzVj
        oxyMRGbp9p7EnQ1rf1OMtwalY6+iLJnlVtqi1vwzKbUu0+JI+rcssUQZ7iMgEdNK
        jeAhw8k6nUfaWBLm/tL7HpzOyYX4LXpDdDQuXr3G6zWlVFOLZJ027GwIums/JmcC
        +empcnndvN1zWjJX3GvqeML3dSzyFuMFMSSc2RG2ADSFU87NL/zjh57MphRL40Hz
        /W10jTrDPUQFSEJBKYbjsL8zWMdv69OUlumpwAxR0MZXMgEFR/xnvu2NALveVNgj
        EYX3zQWe644dvIBps2cJJxg7bnZovq5kfFbXwnmGwXU3QwTdWuBTZzMO3kdj0etQ
        uIvUm0/VT4ZvHI6nIrBcnlzOA8XMnLL2DdQ7orvJkmDX6NfUn8cMmTN+oyeHhxkp
        seYQRygNGmJEbkaQ37ikJtd2lrs7Q2m+gAghjCIFclGSiDsZvsKjTgGpsWIY3ZWs
        qdu09dawRaZYvTD2E64eP4D3do/Hb6s9tXnWR0dYSsszTMKhtJ9cIRa5MCf8RmH6
        MxteGCzVlUG56S6fTvWwbVa6LvG8sBar1qKrg1MiEJ5DaqKOl5n04Da7gFl7hjHF
        nrJVpwDHHYV/L8417bCkCiQJsxDu1jQ49kWLbBdLkmm2Qg1bQQKCAQEA+AuR8cfh
        3CMoQW8vc230toL2eYnTycFwIvMu7zYc+/4Unnr6sGsJiuSbsMRpbf8BhqMX2E3k
        Xmzdv++5CwwcUFywTeenyfJgWzaBh+o+BX/cvWk35s289b7w9zrqNTGcfFmW33hs
        0prGQJM1zQfsiYa4En3S+zo1bVk/lEILJI4u+nANSAeIqBdpciYrxuv+miU0oZzS
        lVC9YfYjPpZZJNWfIbRNZxohuI4ivBTxDow/1OUW7wj1AurG/ZbkE+Ohtd4PezLc
        6CayvO0Z/i6slXCTuDJBk6dkj+OiQq+rWFxYCt0vrtgg5rpAoKRy6dzjyMELP4jd
        n80mPQeI0vEIdQKCAQEAz5yKpnfDBX715xHIJ9pSAeWPg7R+043qSv6bSOmQbVDJ
        i4oSJiVfm0DPaBox9QT8VcBYC3OynDWnh8GMpps8En/ZKEucQRnDu70epjhUYMb/
        NGwBzbd82Y8nHVfr/oUvPMh4+6SMbpur0FNhHKx8m212Dp86Qj+R3SclQpPJnGxF
        0eBntTWwqJ6cpTWv04Tpbre94KeRbnTESepuBFyp+dSi56GKpdq2rY7S0XT7eRqf
        mmxwtURWzVIRgb1e/L/QxjHnQPYDAD3pQ24/71M+a2SZtLVZJ2U2GZ1/wQAs/VBS
        Hmwf7wwYuUmaMM0NSRJrspTDmCUf5U7lNz+cS/g/GQKCAQEA0aIVql3gCQi9kO/D
        Dq8zTrzISlet4qnVd/RHCmyVenN2Qap2DHuqCPTEkFSvNgN66qsUD/9krlkb4Idd
        wHRvyYtMhcrvB8IMpYofVxslZ8h0arBuSmY++QJy7L+iCWrwcjfVRvCkKCoeu5yu
        r6Wux1xQXXBxy1mapdvz2/0lJbP1CDuDPgj/+fAvcgXIocn515TyMlQztXYTWKOJ
        je/LT1Irt3SGpkhzj2KxAHxCbqUhnXAwPb04NUru+ot4H0cW+HnAY8LM6HcsQHey
        rBwOSA5pChePTJcAaotcKzgEfB0vW58sGX0X8WggDqRtajEBYj2koAGwLMpZMuMX
        RA/psQKCAQEApBt9jbDFO6bsAccQjFAK2uz20IjwZ5GaTcWMQco+G+rsJZzyU6zf
        Mf289PEf5CoYvD/aWNMPsGLJFopr/5ZdmdHteeiqjtsq2U/Y1lNYf1dNi8aEdnRA
        AEkkBhHlvb7RZB6jY2biitwKqBYAgYXmyYVw+IXsq0lMp5+12Dax+y+q0QetcpQK
        HH+kGwOhBHXff2FGejp6vvEV58ejR1doFM98JdSPoCKOnAp1opPx4/yjhJGLVf27
        D3l71S4301pcUQ5JWhQcsyg9JswTRb5rbMCMr0daPcXHSeAxiAH3jhTblKirZW4O
        bQg9Fa5Afi5Na1AkfDN8TupaTZ2+kl6coQKCAQA/F0Ub0jnkA9IF6yYfIjlKlThB
        iVfJnAfYV8H1bb5a33dnZ/WOmeffkhJ/5foCg4fI9neDalnrsA5I/SK4SFi6qeW9
        fFoT7oFbGIj1U9aw0GtDhDSGN7MxGKAg21drxznhR8nL+/mgV63vAY4gtRB9yhNE
        IbZUN1unJdL5Ex8jlUgU87gNk7hd0TeVXDNph7i3rkhdfBUiuGuJ1ZjFqW4DhF0b
        8IUVHbVR22yaTuns12xu94dBDe9lWdQ40sAuSWOyO3nRoVlDgJb+8eQLSQs9oKvP
        WoA/NsEGB+dwEKmZJ2wpDIXzvpOro+0KUSJGNWRBrzL2f69Zgldb1yNmtGGg
        -----END RSA PRIVATE KEY-----
      ssl_crt: |
        -----BEGIN CERTIFICATE-----
        MIIFpzCCA4+gAwIBAgIJAMLzkyNyXM/VMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNV
        BAYTAkVTMQ8wDQYDVQQIDAZNYWRyaWQxDzANBgNVBAcMBk1hZHJpZDEVMBMGA1UE
        CgwMVHJhZWZpay10ZXN0MRAwDgYDVQQLDAdUZXN0aW5nMRAwDgYDVQQDDAcqLmxv
        Y2FsMB4XDTE2MDYwNzEwMjMzOFoXDTIxMDYwNzEwMjMzOFowajELMAkGA1UEBhMC
        RVMxDzANBgNVBAgMBk1hZHJpZDEPMA0GA1UEBwwGTWFkcmlkMRUwEwYDVQQKDAxU
        cmFlZmlrLXRlc3QxEDAOBgNVBAsMB1Rlc3RpbmcxEDAOBgNVBAMMByoubG9jYWww
        ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDJKQhm+Cy+JLz85eUaYe6t
        w2Qpl5YyH5zDPcpnFuBsWmqkG6MEw8vzQu3z85sp9VnNpzwkKVARuZCIY5nC4Jt2
        bNVLxuY6VxpbF07ZVge4tb8675ZUga81O2km++iq3GKpYSyHYXOtivGmqOiqHAXH
        k32CmsCP6LjwB2BSHKiQjwCaulHoHbieiN8+v5x7OyqI+gL6zFApLN9P+SLfeVr8
        UDK1QlJnrf382eQBXtoEuBzvSnqAK1lodX44wE3qN608DafwulO3OyBY6n0JS/86
        SX4KbPUZt07Ef0g0a17wXuUhWWZdcC+e/KNk0wo9k/dDb8wvqhU1K18A1M0ap8LM
        Ii1V8rK5d93q2mSe+1qhinrmwuE6/ELDWVz4ggTybwxCIXnYYt85myvgW2HLyGDx
        bAl6AG6RbV2KTxEgVLQslH2qxfiaCxLomwXjUpzmjVLkd1otPg++rnRIDFIwcUcb
        vqkA0lYRoqshUwrP8Atzryux+wJzNDNPFWKgbECfploD60/sxbijvVm8LGI2z8x2
        UK+gHMxz1zvG8zKbjwJRXhL5vTx+aKxHh4v4a89i5dR6GFFAU4OMJ/M9/05/Tyez
        anX2dUdH+0/1PGnxq2cKxsNSM3t57GCeRQiJXK4RZw3JG0NEml7K3R/Q5WewdHYn
        bYMi7/c3cg95QlGMYvaebQIDAQABo1AwTjAdBgNVHQ4EFgQUzzBk0Sf/aGcO1z/H
        qf5YmlCVYI8wHwYDVR0jBBgwFoAUzzBk0Sf/aGcO1z/Hqf5YmlCVYI8wDAYDVR0T
        BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAc6B5m9WWCHXPXOJNRnUuxC63ETNS
        Ir/IbkMV8TYaovUr0tlf5TIPFCQ7eqNJcTb2aAQO3w+F0Wddc5i1WSbkCUV75x7L
        iHmktwO81XS9XZlkpo4+O2IU8oKhwF70bPn/wM5Kyb0aykJAdDSpwRagcYn7Vdk7
        U/C4MiEaXlnvc9CTNWT+NoI4IEaKntimqS+k193Yxo9fOqmo2v0eiuAeOy9PJvLo
        qBBh9Tz7yuUdOLbUWsqXaFL2VBecKehorS/zrh8CbNuIG/9HEjVWOFAONoqWX7Qz
        77QSVJVhgxk+N/agY9v0ov66W0vEyhHndvdHQg70feyVL8L9g82Uis3a2wA/82Zp
        nxRNoVddro0wQDMWEf5sGHZXoG+aY/CsWT35A5NHdMaVirPDvE38GhxBwDmk8uo1
        NaswgbCwZHU30vvLPvHumfUFYWurPtkrZ2gqSqxewwgXOo9m14FxQhE9U7ax5ZSY
        ji6JqNHQk8F1scCn9L0iX7yDcCFPRvzvB2mOGRGdVWrk6dx3XR0jpLOyEausM07a
        rsdpTYCWNsbLafsTGbIWc/ddhb9SN+fnWLDpNSXKN9IU5tzUuA60ZP4lfPun26L8
        7l4ZF1JEN6lui55Z0Vfo0vB7oGVT64SLiigbTDl1LrrusqOpPXOPzvNEfUQ5Zhhi
        x8NPFRMB44AWyLI=
        -----END CERTIFICATE-----
